#!/bin/bash
set -e

# Configuration
APP_NAME="vozes"
VERSION="${VERSION:-1.6.0}"

# Ensure deb build exists to reuse its files
# Detect architecture
if command -v dpkg >/dev/null 2>&1; then
    DEB_ARCH="$(dpkg --print-architecture)"
else
    UNAME_M=$(uname -m)
    if [ "$UNAME_M" = "x86_64" ]; then
        DEB_ARCH="amd64"
    elif [ "$UNAME_M" = "aarch64" ] || [ "$UNAME_M" = "arm64" ]; then
        DEB_ARCH="arm64"
    else
        DEB_ARCH="$UNAME_M"
    fi
fi

DEB_NAME="${APP_NAME}_${VERSION}_${DEB_ARCH}"

if [ ! -d "$DEB_NAME/usr" ]; then
    echo "Build directory not found. Running build_deb.sh to compile whisper-cli and set up files..."
    ./build_deb.sh
fi

# Determine Arch Linux architecture name
if [ "$DEB_ARCH" = "amd64" ]; then
    ARCH_NAME="x86_64"
elif [ "$DEB_ARCH" = "arm64" ]; then
    ARCH_NAME="aarch64"
else
    ARCH_NAME="any"
fi

ARCH_PKG_NAME="${APP_NAME}-${VERSION}-1-${ARCH_NAME}.pkg.tar.zst"
echo "Building Arch Linux package: $ARCH_PKG_NAME"

# Create temporary directory
rm -rf archpkg
mkdir -p archpkg/usr
cp -r "$DEB_NAME/usr/"* archpkg/usr/

# Get size of the usr directory in bytes
SIZE=$(du -sb archpkg/usr | cut -f1)
BUILDDATE=$(date +%s)

# Create PKGINFO file
cat <<EOF > archpkg/.PKGINFO
# Generated by build_arch.sh
pkgname = ${APP_NAME}
pkgver = ${VERSION}-1
pkgdesc = Professional voice dictation system for Linux using native whisper.cpp.
url = https://github.com/InledGroup/vozes
builddate = ${BUILDDATE}
packager = Inled Group <hi@inled.es>
size = ${SIZE}
arch = ${ARCH_NAME}
license = GPL3
depend = python
depend = python-gobject
depend = gtk4
depend = libadwaita
depend = cairo
depend = portaudio
depend = libevdev
depend = alsa-lib
depend = libpulse
EOF

# Create .INSTALL file
cat <<EOF > archpkg/.INSTALL
post_install() {
  echo "Setting up Vozes environment..."
  cd /usr/share/vozes
  
  # Create virtual environment
  python3 -m venv venv --system-site-packages
  source venv/bin/activate
  pip install --upgrade pip
  
  # Install python requirements
  pip install -r requirements.txt
  pip install openwakeword==0.6.0 --no-deps
  
  # Download wake word models
  echo "Downloading wake word models..."
  python3 -c "from openwakeword.utils import download_models; download_models()"
  
  # Reload udev rules
  echo "Reloading udev rules..."
  udevadm control --reload-rules || true
  udevadm trigger || true
  
  # Ensure input group exists
  getent group input >/dev/null || groupadd -r input
}

post_upgrade() {
  post_install
}

pre_remove() {
  echo "Cleaning up Vozes environment..."
  if [ -d "/usr/share/vozes/venv" ]; then
    rm -rf /usr/share/vozes/venv
  fi
}
EOF

# Build package
if command -v tar >/dev/null && command -v zstd >/dev/null; then
    cd archpkg
    tar --owner=0 --group=0 -cf - .PKGINFO .INSTALL usr | zstd -z -19 > "../${ARCH_PKG_NAME}"
    cd ..
    echo "Arch Linux package built successfully: $ARCH_PKG_NAME"
    rm -rf archpkg
else
    echo "Error: 'tar' or 'zstd' not found. Cannot compile Arch package."
    exit 1
fi
